Support generate_load_scripts.
ionide/ionide-vscode-paket pull request #34
Opened 2017-03-16 11:59 UTC by isaacabraham

2017-03-16 11:59 UTC, forki requested changes

2017-03-16 11:59 UTC, forki commented on src/paket.fs
> +                        | PaketTag "generate_load_scripts:" -> [ "true"; "false" ] |> concatAndLift
I think it's on vs. off

2017-03-16 12:00 UTC, forki commented on src/paket.fs
> +                        | PaketTag "generate_load_scripts:" -> [ "true"; "false" ] |> concatAndLift
or maybe it isn't and I just did it wrong in lockfile

2017-03-16 12:01 UTC, forki commented on src/paket.fs
> +                        | PaketTag "generate_load_scripts:" -> [ "true"; "false" ] |> concatAndLift
ok just checked. all is well.

2017-03-16 12:01 UTC, forki approved these changes

2017-06-17 21:37 UTC, merged

2017-06-17 21:37 UTC, Krzysztof-Cieslak commented
Uhh... not sure how I've missed this PR :(

2017-06-19 08:12 UTC, isaacabraham commented
Eh? This has been in Ionide for ages now, hasn't it?

2017-06-19 08:58 UTC, Krzysztof-Cieslak commented
This PR adds `generate_load_scripts` to `Paket.dependencies` autocomplete